name: NPM Dev site CI/CD

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'src' # Here the path to the folder where package-lock.json is located.
    strategy:
      matrix:
        node-version: ['16.x'] # [12.x, 14.x, 16.x]
    steps:
    - uses: actions/checkout@v3
      with:
        ref: dev
    - run: ls
    # && cd src && ls
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
